# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/repozytorium/Hangman-Game/test.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setStyleSheet("*{\n"
                                 "background-color: #5F9494;\n"
                                 "}\n"
                                 "\n"
                                 "#button_next_letter, #button_next_word , #button_len_password, #button_multiplayer ,#button_computer, #button_entry, #button_hack{\n"
                                 "background-color: #D9D9D9;\n"
                                 "border-radius : 15px;\n"
                                 "}\n"
                                 "\n"
                                 "#lineEdit, #lineEdit_2{\n"
                                 "border: 5px solid #D9D9D9;\n"
                                 "border-radius:15px\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.menu_page = QtWidgets.QWidget()
        self.menu_page.setObjectName("menu_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_multiplayer = QtWidgets.QPushButton(self.menu_page)
        self.button_multiplayer.setMinimumSize(QtCore.QSize(300, 100))
        self.button_multiplayer.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_multiplayer.setFont(font)
        self.button_multiplayer.setObjectName("button_multiplayer")
        self.verticalLayout.addWidget(
            self.button_multiplayer, 0, QtCore.Qt.AlignHCenter)
        self.button_computer = QtWidgets.QPushButton(self.menu_page)
        self.button_computer.setMinimumSize(QtCore.QSize(300, 100))
        self.button_computer.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_computer.setFont(font)
        self.button_computer.setObjectName("button_computer")
        self.verticalLayout.addWidget(
            self.button_computer, 0, QtCore.Qt.AlignHCenter)
        self.button_hack = QtWidgets.QPushButton(self.menu_page)
        self.button_hack.setMinimumSize(QtCore.QSize(300, 100))
        self.button_hack.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_hack.setFont(font)
        self.button_hack.setObjectName("button_hack")
        self.verticalLayout.addWidget(
            self.button_hack, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.menu_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.button_entry = QtWidgets.QPushButton(self.page_2)
        self.button_entry.setMinimumSize(QtCore.QSize(300, 100))
        self.button_entry.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_entry.setFont(font)
        self.button_entry.setObjectName("button_entry")
        self.verticalLayout_3.addWidget(
            self.button_entry, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_6 = QtWidgets.QWidget(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout_8.addWidget(self.widget_7, 0, QtCore.Qt.AlignTop)
        
        self.verticalLayout_5.addWidget(self.widget_6, 0, QtCore.Qt.AlignTop)
        self.widget_4 = QtWidgets.QWidget(self.page_4)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_next_word = QtWidgets.QPushButton(self.widget_4)
        self.button_next_word.setMinimumSize(QtCore.QSize(300, 100))
        self.button_next_word.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_next_word.setFont(font)
        self.button_next_word.setObjectName("button_next_word")
        self.horizontalLayout_6.addWidget(self.button_next_word)
        self.button_len_password = QtWidgets.QPushButton(self.widget_4)
        self.button_len_password.setMinimumSize(QtCore.QSize(300, 100))
        self.button_len_password.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_len_password.setFont(font)
        self.button_len_password.setObjectName("button_len_password")
        self.horizontalLayout_6.addWidget(self.button_len_password)
        self.verticalLayout_5.addWidget(
            self.widget_4, 0, QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.page_3)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.widget)
        self.show_password = QtWidgets.QWidget(self.page_3)
        self.show_password.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.show_password.setFont(font)
        self.show_password.setObjectName("show_password")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.show_password)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4.addWidget(
            self.show_password, 0, QtCore.Qt.AlignLeft)
        self.stackedWidget.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        self.label_8.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(
            self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.widget_5 = QtWidgets.QWidget(self.page_5)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7.addWidget(
            self.widget_5, 0, QtCore.Qt.AlignHCenter)
        self.button_next_letter = QtWidgets.QPushButton(self.page_5)
        self.button_next_letter.setMinimumSize(QtCore.QSize(300, 100))
        self.button_next_letter.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_next_letter.setFont(font)
        self.button_next_letter.setObjectName("button_next_letter")
        self.verticalLayout_7.addWidget(
            self.button_next_letter, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_multiplayer.setText(
            _translate("MainWindow", "MULTIPLAYER"))
        self.button_computer.setText(_translate("MainWindow", "COMPUTER"))
        self.button_hack.setText(_translate("MainWindow", "HACK"))
        self.label_2.setText(_translate("MainWindow", "PASSWORD : "))
        self.button_entry.setText(_translate("MainWindow", "Entry"))
        self.label_6.setText(_translate("MainWindow", "How many words : "))
        self.button_next_word.setText(_translate("MainWindow", "next word"))
        self.button_len_password.setText(_translate("MainWindow", "finish"))
        self.label_3.setText(_translate("MainWindow", "LETTERS :"))
        self.button_next_letter.setText(
            _translate("MainWindow", "next letter"))
